<section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Terms & Condition</h2>
          <ol>
            <li><a href="<?php echo site_url(); ?>">Home</a></li>
            <li>Terms & Condition</li>
          </ol>
        </div>

      </div>
    </section>
<section id="team" class="team ">
      <div class="container">
      
        <div class="row">
          <p>जैसे ही आप लोग मेरा मशीन का फॉर्म यानि जानकारी सबमिट करते हैं आपकी जाहिरात करने हेतु हम आपकी जानकारी सार्वजनिक तौर पर हमारी ऐप और वेबसाइट के ऊपर दिखाएंगे हम आपका मोबाइल नंबर एड्रेस यह सब चीजें कस्टमर को प्रदान करेंगे जिस कारण आपको आपके कस्टमर से फोन कॉल्स भी आ सकते हैं कई बार आपकी इसमें गलतफहमी या आपके साथ में धोखा भी हो सकता है पर आपको कोई भी अर्थीक या कोई भी बड़ा फैसला लेने से पहले आपको खुद ही जांचपड़ताल करना होगा  फैसला पूर्णता आपके ऊपर ही होगा इसीलिए मेरा मशीन आपसे कोई भी आदमी से या कंपनी से व्यवहार,नौकरी तथा गठबंधन उसे जबाबदार नहीं है या मेरामशीन किसी की भी शिफारिश भी नहीं करेगा  सब जानकारी हम केवल आपको हमे  प्राप्त हुए जानकारी से ही देंगे 
हम सिस्टीम या मोबाइल में कुकीज़ या नोटिफ़िकेशंन दे सकते है ताकि आपको meramachine का बेहतर अनुभव हो|  
वह जानकारी कितनी प्रतिशत सही है ये आपको ही देखना है और आपको ही स्वयं निर्णय लेना है की आप हमारे एप या वेबसाइट के फॉर्म या जानकारी भरे या नहीं भरे
हम आपकी जानकारी का उपयोग उचित तरीके से यानी केवल मिशनरी कार्यों के लिए करेंगे और हम आपकी जानकारी को वेबसाइट पर प्रकाशित करके अन्य लोगों से शुल्क भी एकत्र कर सकते हैं, लेकिन यदि जानकारी का दुरुपयोग किसी और द्वारा किया जाता है, तो मेरामशीन  जिम्मेदार नहीं होगी और हम दुर्व्यवहार तथा  अप या वेबसाइट का गलत इस्तेमाल करने वाले को कोर्ट में खींच सकते है | 
और ड्रायवर ऑपरेटर को नौकरी देना हो,मशीन खरेदी,बेचना या किसके पास नौकरी करना  कोही भी हमारी सर्विस(meramachine app or website) इसे आपको ही जांच करके लेनी है| लिखित पाठ में हमारा या हम का  मतलब मेरा मशीन या वेबसाइट से है और आप या आपका मतलब उस ग्राहक से है जो मेरा मशीन में फॉर्म जमा करता है और ड्राइवर ऑपरेटर मशीन मालिक मशीन विक्रेता आदि सहित सभी लोगों की जानकारी भरता है।
उचित जानकारी नहीं समझी हो या उसमें कोई अच्छा बदलाव हो तो हमें आप ईमेल  कर सकते हैं| </p>
<p>As soon as you submit the form of meramachine i.e. information, we will show your information publicly on our app and website to advertise, we will provide your mobile number address, all these things to the customer, due to which you will get phone calls from your customer. Many times there may be misunderstanding or cheating with you, but before taking any economic or any big decision, you have to investigate yourself, the completeness of the decision will be on you, meramachine is not responsible for that. Dealing, job and alliance with or from the company is not responsible or meramachine will not even recommend anyone, we will give all the information to you only from the information received by us.
We may provide cookies or notifications in the system or mobile to give you a better experience of meramachine.
You have to see how much percentage of that information is correct and you have to decide for yourself whether you fill the form or information of our app or website or not.
We will use your information in a proper manner i.e. only for machinery work and we may also collect fee from other people by publishing your information on website but if information is misused by someone else, meramachine is not responsible And we can drag anyone who misbehaves and misuses you or website to court.
And if you want to give a job to a driver operator, buy, sell or employ a machine, you have to check our service (meramachine app or website) and take it yourself. 
(In the written text our or we means meramachine or website and you or your means the customer who submits the form in my machine and fills the information of all persons including driver, operator, machine owner, machine seller and buyer etc.)
If you have not understood the proper information or if there is any good change in it, then you can email us.</p>
        <p>Please read these terms and conditions ("Terms") carefully before accessing or using the Platform These Terms along with the Privacy Policy published on the Platform ("Privacy Policy") and other policies (as may be notified/displayed/published on the Platform) constitutes the contract between the Users of this Platform and Company (collectively "Agreement"). By use of the Platform, Users agree to be bound by these Agreement as posted on the Platform from time to time.</p>
               
<p>meramachine (mm) to provide job placement machinary like jcb,poklain,roller,hyva any we machine like tata,escorts jcb construction machinary  is an application which provides an online marketplace ("Application") where registered suppliers ("Suppliers") can offer to sell their products to registered users of Application including to resellers ("Resellers") and other Users The Application and the website at www.meramachine.com ("Website") (collectively, "Platform") are operated by meramachine.
<p>The We’s role is limited to the managing Application and associated marketing, facilitating payment collections, fulfilment, order management, enquiry management and other incidental services to enable the transactions between the Suppliers and the Reseller ("Services").</p>
<p>Services are not made available on the Website and to avail the same, Users are required to install the Application. The Agreement is applicable to any person when they install, download or even merely visit or access any part of the Platform or utilise the Services, such persons are referred to as users, which include without limitation users who are browsers, Suppliers, Resellers, merchants, other purchaser or contributors of content (collectively, "User"). The Agreement between User and We is effective on the date on which the Application is downloaded/Website is accessed and/or the date on which terms of Agreement are updated, creating a legally binding arrangement between the User and the We.</p>

<p><b>Agreement can be modified?</b></p>
<p>Users can review the most current version of the Agreement at any time on the Website. We reserves the right to unilaterally update, change or replace any part of the Agreement by publishing updates or changes on the Platform and such amended provisions of the Agreement shall be effective immediately upon being posted on the Platform.</p>
<p>It is the responsibility of the Users to check this page periodically for changes. The Users’ continued use of or access to the Application following the posting of any changes constitutes acceptance of those changes.</p>
<p>Once you fill your information, it cannot be deleted or updated, so fill the correct information at the time of filling the form. Next time, if you want to update the form or update the information, you will have to fill another form and its charges will be different. You may share the information with the user side or other people as long as you want to show it Also, all time subsciption mins as long as the Mera Machine website is up and running, you should also note that sharing your information is our job and we can make money from it. You will not have any share.</p>
<b>What if the terms of the Agreement are not acceptable to User?</b>
<p>If the User does not agree with the terms of the Agreement, the User is advised to refrain from using the Platform. By accessing or using the platform, the user irrevocably accepts the Agreement and agrees to abide by the same (as updated from time to time).</p>
<b style="color:red;">ACCOUNT REGISTRATION, SUSPENSION AND TERMINATION</b><br>
<p>You can use Mera Machine for free but we may publish your information after you fill the form. If Mera Machine and we feel that you are doing something wrong, we may close your account without informing you. Within 6 months after you mail meramachine otherised mail we can provide your reasons and after we decide your account may continue or stop your service</p>
<b>Does a User necessarily need to create an account on the Platform?</b>
<p>We does not permit Users to avail the Services on the Platform without prior registration. Users may access the Application by registering to create an account and become a member. The membership is limited for the purpose of buying or selling products, is subject to this Agreement and strictly not transferable.</p>
<b>For the use of Platform, is a User subject to any eligibility criteria?</b>
<p>The Services on the Platform shall be availed by User(s) who can form legally binding contracts under Indian Contract Act, 1872 and are at least eighteen (18) years of age.</p>
<p>The Company reserves the right to terminate the Users account and / or deny access to the Platform if it is brought to the Company’s notice or if it is discovered that the User does not meet the conditions herein. User(s) accessing or using the Platform represent and warrant that they have the right to access or use the Platform.</p>
<b>Are there any specific requirements for registering an account on Platform?</b>
<p>The Users are required to enter a valid phone number while registering on Platform. By such registration, User consents to be contacted by Company via phone calls, SMS notifications, instant messages or other such means of communication inter alia for subscription/services/promotional updates etc. Users may 'opt-out' of such subscription/service/promotional updates either through the ‘opt out’ means provided or by writing to the support team</p>
<p>It is the responsibility of the Users to provide correct mobile number so that the Company can communicate with the Users via SMS. The Users understand and agree that if the Company sends an SMS but the Users do not receive it because the Users’ mobile number is incorrect or out of data or blocked by the User's service provider, or the Users are otherwise unable to receive SMS, the Company shall be deemed to have provided the communication to the Users effectively.</p>
<p>It is the User’s responsibility to provide accurate, current and complete information during the registration process and to update such information to keep it accurate, current and complete</p>
<b>Can User account registered on Platform be suspended or terminated?</b>
<p>does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between Reseller and its end user/consumer.
Policies related to returns/ exchanges, penalties, refunds, cancellation will be updated in the Application from time to time. The Company holds the right to change these policies as required in the Application without any permission from the Users.</p>
<b>How does payment and settlement of payment work on the Platform?</b>
<p>The Users acknowledge and agree that the Company may, at the request of the Supplier or the Reseller, act as the payment agent for the limited purpose of accepting payments on behalf of such Suppliers and Resellers. The Users understand, accept and agree that the payment facility provided by the Company is neither a banking nor financial service but is merely a facilitator providing a third party payment processor for the transactions on the Application. Further, by providing payment facility, the Company is neither acting as a trustee nor acting in a fiduciary capacity with respect to the transaction or the transaction price. The Company will not be liable for any charges made by the Users bank in relation to payment of the total amount.</p>
<p>In connection with any order, information such as name, billing address and credit card information may need to be provided either to the Company or the third party payment processor. If the Users are directed to the third party payment processor, they may be subject to terms and conditions governing use of that third party’s service and that third party’s personal information collection practices. Users are requested to review such terms and conditions and privacy policy before using the Application. In case of Reseller providing billing information, delivery address or other contact information of its end user/consumer to Company or other delivery service provider, Reseller shall ensure that it has necessary consents and approvals from the respective end user/consumer as may be required under applicable law.</p>
<p>Company merely collects the payment on behalf of the Supplier or Reseller, as the case may be. All applicable taxes and levies, the rates thereof and the manner of applicability of such taxes are to be charged and determined by the Supplier or Reseller. Company holds no responsibility for the legal correctness/validity of the levy of such taxes. The sole liability with respect to any legal issue arising on the taxes payable shall be with the Reseller.
The transaction is bilateral between Suppliers & Users and/or Reseller & end users/consumers ("User Transactions"), the Company is not liable to charge or deposit any taxes applicable on such transaction.</p>
<b>Whether Company charges User(s) for Services provided by Company on the Platform?</b>
<p>Services on Platform may require payment of charges, rate of which shall be solely at the discretion of the Company and shall be subject to User approval at the time of placing an order on the Platform. Company reserves the right to revise charges towards Service at any time at its sole discretion. The charge, applicable at any given time, will be the charge displayed at the time of purchase/booking of the respective Service (if any) by User on the Platform.
Company reserves the right to introduce additional chargeable services on the Platform including charges for a premium return service, cancellation charges, cash on delivery handling fees etc.</p>
<b>Whether for transacting on Platform, User is required to be registered under the Central or State Goods and Services Tax Legislations ("GST Laws")?</b>
<p>Company is not obligated towards any direct or indirect tax obligation of the User that may arise as a result of User's access or use of Services on the Platform. The requirement for registration and compliances under the GST Laws and other tax laws is the sole responsibility of the User including Reseller, the Company is not liable for any omissions or commissions by such User who acts in violation of the any applicable law. Accordingly, User is advised to seek independent tax advice relating to its business and/or transaction through Platform including whether it is liable for GST registration.</p>
<b style="font-size:16px;">USE OF THE PLATFORM</b>
<p>Company endeavours to make the Application available 24X7. However, the Company does not represent that access to the Application will be uninterrupted, timely, error free, free of viruses or other harmful components or that such defects will be corrected.</p>
<p>Users understand and acknowledge that the use of Application requires internet connectivity and telecommunication links. Users shall bear the costs incurred to access and use the Application and avail Services, and Company shall not, under any circumstances whatsoever, be responsible or liable for such costs.</p>
<p>Company does not warrant that Application will be compatible with all hardware and software which is used by Users.</p>
<p>Application may be under constant upgrades, and some functions and features may not be fully operational. Application is provided on an 'as is' and 'as available' basis. Company expressly disclaims all warranties of any kind, whether express or implied with respect to the records and other data that is made available by it to Users.
Users shall be solely responsible for damages to their data system or for loss of data arising from download of content from Application. No guidance or information, written or oral, obtained from Company or via Platform, shall constitute any warranty, unless stated otherwise.</p>
<p><b>Does the Company guarantee performance of the agreement or other arrangements inter se between User(s) or otherwise in respect of products on Platform?</b></p>
<p>Company, through Platform, is a mere facilitator of the transaction including between Supplier and User and is not responsible for any non-performance or breach of any contract entered into towards User Transactions. The Company cannot and does not guarantee that the concerned Suppliers will perform any transaction concluded on the Platform. The Company shall not and is not required to mediate or resolve any dispute or disagreement between the Users concerned including with any other third party.</p>
<p>The Company does not represent any of User or Supplier, and disclaims any liability with respect to any error or inconsistency with respect to any information relating to such Supplier or User displayed on the Platform.</p>
<p>The Company does not make any representation or warranty as to the item-specifics (such as legal title, creditworthiness, identity, etc.) of any of its Users. Company shall not be liable for any misuse of information shared by Users with it; or through the Users profile; or with a third party on the Platform, chat rooms, forums, or comments.
Users acknowledge and agree that the Company is not an arbitrator or judge of disputes concerning intellectual property and it cannot, by any means, verify that any Supplier or Reseller selling or supplying merchandise on/through the Platform have the right to sell the products. Company encourages Users to assist it in identifying listings on the Platform, which, according to the Users’ knowledge or belief infringe their rights or third party rights.
Company does not at any point of time during any transaction between any Supplier and a User take possession of any product offered nor does it at any point gain title to or have any rights or claims over such products. At no time shall the Company hold any right, title or interest over the products nor shall the Company have any obligations or liabilities in respect of such contract entered into between the Users. Company is not responsible for damages or delays as a result of products which are out of stock, unavailable or back ordered.</p>
<b>Whether the use of Platform (a) is restricted in any manner; and (b) requires any generic compliances from User?</b><br>
<p>User should not use the Platform to host, display, upload, download, modify, publish, transmit, update or share any information which:</p>
<p>
is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, slanderous, criminally inciting or invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatsoever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;<br>
is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;<br>
harasses or advocates harassment of another person;<br>
infringes upon or violates any third party’s rights including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person’s name, email address, physical address or phone number) or rights of publicity;<br>
promotes an illegal or unauthorized copy of another person's copyrighted work, such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices;<br>
tries to gain unauthorized access or exceeds the scope of authorized access to the Application or to the profiles, blogs, communities, account information, or other areas of the Application or solicits passwords or personal identifying information for commercial or unlawful purposes from other Users;<br>
interferes with another User’s use and enjoyment of the Platform or any third party users enjoyment of similar services;<br>
refers to any website or URL that, in our sole discretion, contains material that is inappropriate for the Platform or any other website, contains content that would be prohibited or violates the spirit of these Terms;<br>
violates any law for the time being in force;<br>
impersonates another person;<br>
contains software viruses or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information; and
directly or indirectly, offers, attempts to offer, trades or attempts to trade in any item, dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.
When accessing or using the Platform or availing the Services, the User has to comply and ensure the following:<br>
All registration information submitted by User is truthful, lawful and accurate;<br>
User's use of the Application/Platform shall be solely for their use and they shall not authorize others to use the account;<br>
User does not submit, post, upload, distribute, or otherwise make available or transmit any information that: (i) is defamatory, abusive, harassing, insulting, threatening, or that could be deemed to be stalking or constitute an invasion of a right of privacy of another person; (ii) is bigoted, hateful, or racially or otherwise offensive; (iii) is violent, vulgar, obscene, pornographic or otherwise sexually explicit; (iv) is illegal or encourages or advocates illegal activity or the discussion of illegal activities with the intent to commit them;<br>
All necessary licenses, consents, permissions and rights are owned by Users and there is no need for any payment or permission or authorization required from any other party or entity to use, distribute or otherwise exploit in all manners permitted by the Agreement, all trademarks, copyrights, patents, trade secrets, privacy and publicity rights and / or other proprietary rights contained in any content that Users submit, post, upload, distribute or otherwise transmit or make available; 
</p>
<p>User will not use Platform in any way that is unlawful, or harms the Company or any other person or entity;<br>
User will not post, submit, upload, distribute, or otherwise transmit or make available any software or other computer files that contain a virus or other harmful component, or otherwise impair or damage the Platform or any connected network, or otherwise interfere with any person or entity’s use or enjoyment of Application;<br>
User will not use another person’s username, password or other account information, or another person’s name, likeness, voice, image or photograph or impersonate any person or entity or misrepresent your identity or affiliation with any person or entity;<br>
User will not or attempt to delete or modify any content of Platform, including but not limited to, disclaimers or proprietary notices such as copyright or trademark symbols, logos;<br>
User will not post or contribute any information or data that may be obscene, indecent, pornographic, vulgar, profane, racist, sexist, discriminatory, offensive, derogatory, harmful, harassing, threatening, embarrassing, malicious, abusive, hateful, menacing, defamatory, untrue or political or contrary to our interest;<br>
User shall not access Platform without authority or use Platform in a manner that damages, interferes or disrupts, any part of Platform or any equipment or any network on which Platform is stored or any equipment of any third party;<br>
User shall not attempt to gain unauthorized access to any portion or feature of the Application, or any other systems or networks connected to the Platform by any means. User shall not probe, scan or test the vulnerability of Platform nor breach the security or authentication measures on Platform or any network connected to Platform.<br>
User agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of Platform or any transaction being conducted on Platform, or with any other person’s use of Platform. User may not use Platform or any of its content for any purpose that is unlawful or prohibited by this Agreement.<br>
User shall at all times ensure full compliance with the applicable law, as amended from time to time, including that of (i) the Information Technology Act, 2000 and the rules thereunder; (ii) all applicable domestic laws, rules and regulations (including the provisions of any applicable exchange control laws or regulations in force); and (iii) international laws, foreign exchange laws, statutes, ordinances and regulations (including, but not limited to Direct and Indirect Taxes applicable as per current statue in the country) regarding the use of the Application and listing, purchase, solicitation of offers to purchase, and sale of products or Services. User shall not engage in any transaction which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force.<br>
In order to allow Company to use the information supplied by the Users, without violating any rights or any laws, Users agree to grant Company a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights. Company will only use the information in accordance with this Agreement, applicable to use of Platform and for provision of Services.<br>
Company shall at times and at their sole discretion reserve the right to disable any user identification code or password if any User has failed to comply with any of the provisions of this Agreement. Company shall have all the rights to take necessary action and claim damages that may occur due to User's involvement/participation in any way either on their own or through group/s of people, intentionally or unintentionally in hacking.</p>
<h4 style="text-weight:bold">ACCURACY AND COMPLETENESS OF INFORMATION ON PLATFORM</h4>
<p><b>What is the accuracy and completeness of all information displayed on the Platform?</b></p>
<p>
Company takes all endeavours to the best of its efforts to keep information on the Platform accurate. However, the material and content on the Platform is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or timely sources of information. Reference to paragraph 5.2 below, User will agree that a majority of content including products displayed on Platform are provided by the respective Suppliers, who shall at all times be responsible for provision of information related to such products listed by them. Apart from reasonable checks to ensure general hygiene of Platform, Company does not exercise any control over such content or information.<br>
Company undertakes no obligation to update, amend or clarify information in the Platform, including without limitation, pricing information, except as required by law. Company does not own any responsibility or obligation whatsoever towards either ensuring the accuracy of the information provided by the Users. Any reliance on the material on Platform is at the Users’ own risk.<br>
Platform may contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only. The Company reserves the right to modify the contents of Platform at any time, but has no obligation to update any information on Platform. User is solely responsible to monitor changes to the information on Platform. No specified update or refresh date applied to Platform, should be taken to indicate that all information on Platform or pertaining to the Services have been modified or updated.<br>
Occasionally there may be information on Platform that contains typographical errors, inaccuracies or omissions that may relate to information pertaining to the products, pricing, promotions, offers, shipping charges, transit times and availability. Company reserves the right to correct any errors, inaccuracies or omissions, and to change or update information if any information on Platform is inaccurate at any time without prior notice.<br>
The Information is provided 'as is' with no guarantee of completeness, accuracy, timeliness or of the results obtained from the use of the Information, and without warranty of any kind, express or implied, including, but not limited to warranties of performance, merchantability and fitness for a particular purpose. Nothing contained in this Agreement shall to any extent substitute for the independent investigations and the sound technical and business judgment of User.<br>
</p>
<p><b>Is information related to products on Platform provided by the Company?</b></p>
<p>
Not all information on the Platform is provided by Company. From time to time, Users who are Suppliers provide information relating to the products proposed to be sold by them and are hence responsible for the same. In this connection, Suppliers undertake that all such information shall be accurate in all respects. Suppliers are discouraged from and should not exaggerate or overemphasise the attributes of such products so as to mislead Users in any manner.<br>
Company reserves the right, but has no obligation, to monitor the materials posted on Platform. Company, however, has the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit of these Terms. In no event shall Company assume any responsibility or liability for any content posted or for any claims, damages or losses resulting from use of content and/or appearance of content on Platform.<br>
Suppliers take sole responsibility for the correctness of the details pertaining to specifics (such as quality, value, saleability, etc.) of the products proposed to be sold or offered to be sold or purchased on Platform. Company does not implicitly or explicitly support or endorse the sale or purchase of any products nor provide any warrantee/guarantee of the products sold to Users, and in no event shall such products be the responsibility of Company. Company does not represent or warrant that the information available on Platform will be correct, accurate or otherwise reliable.<br>
Company is not responsible for any inaccuracy, incompleteness or outdated information made available on the Application, either provided by any User including Suppliers.
</p>
<h3>LISTING AND SELLING</h3>
<p><b>As Supplier, in addition to this Agreement, what other terms is a User required to abide by?</b></p>
<p>
Suppliers, in addition to this Agreement are also bound by applicable laws of India, including without limitation, the following laws:  The Legal Metrology Act, 2009 and Legal Metrology (Packaged Commodities) Rules, 2011 (Packaging Rules);<br>
Drugs and Cosmetics Act, 1940 and Drugs and Cosmetics Rules, 1945 (D&C Rules);<br>
Food Safety and standard Act, 2006, Food Safety and Standard (Packaging and labelling) Regulation 2011, (FSS Packaging Regulation) Food Safety and Standard (Food Product Standard and Food Addictive) Regulation, 2011 (FSS Standard Regulations) and Food Safety and Standard (food or Health Supplements, Nutraceuticals, Food for Special Medical Purpose, Functional Food and Novel Food) Regulation 2016 (FSS Supplement Regulation).<br>
As per above mentioned statutes and regulations and any other relevant law in place during the tenure of this association, Company understands that there is an obligation on Supplier to ensure that the package in which the products are sold complies with labelling and packing requirements and other laws that may be prescribed in this regard. Hence, it shall be the sole responsibility of Supplier to comply with applicable laws and the Company shall not be held responsible in any manner. Suppliers shall indemnify Company and Platform for any harm or loss in relation to contravention of above regulations or other applicable laws.<br>
</p>
<p><b>When can the Suppliers get their products listed?</b></p>
<p>
Suppliers are permitted to list products for sale on the Application in accordance with the terms mentioned in this Agreement and other contract entered into with Company for the said purpose, wherein other rights and obligations of the parties are defined in detail.<br>
By listing its products on the Platform, the Suppliers represent and warrant that they are legally capable to sell or list the products on Platform; and the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of any third party. Suppliers and Users agree that the Company is not responsible for the breach of the same.
</p>
<b style="font-size:15px;">USER INFORMATION AND THRID PARTY TOOLS/LINKS</b><br>
<p><b>What information is collected from the User? How does Company deal with the information provided to it by a User while using Platform?</b></p>
<p>
Company collects various types of information, some information is non-personal information and some is personal information.<br>
All information about Users that are collected, stored or transmitted in any way on Platform is processed for facilitating various operations on Platform, including registration, order placement, listing, or payments.<br>
For a more comprehensive understanding, Users are encouraged to view the Platform’s Privacy Policy available on the Platform.
</p>
<b>Does the Company use Third Party tools on Platform?</b><br>
<p>
The Company may provide User with access to third-party tools over the Platform which Company neither monitors nor has any control nor input. User acknowledges and agrees that access to such tools is on an 'as is' and 'as available' basis, without any warranties, representations or conditions of any kind and without any endorsement by Company. Company shall have no liability whatsoever arising from or relating to your use of optional third-party tools.Any use by the User of the optional tools offered through the Application/Platform is entirely at its own risk and discretion and it is the responsibility of User that it ensures that it is familiar with and approves the terms on which such tools are provided by the relevant third-party provider(s).
</p>
<p>The Company may from time to time, offer new features through Platform which may include the use new third-party tools and resources. Such new features shall also be subject to this Agreement. Complaints, claims, concerns, or questions regarding third-party tools or third party websites should be directed to the third-party.</p>
<p><b>Does Company use third party links or third party tools on Platform? Are these links and tools accurate and secure?</b></p>
<p>Certain content or products available via the Platform may include materials from third-parties. Third-party links on the Application/Platform may direct User to third-party websites that are not affiliated with the Company. The Company is not responsible for examining or evaluating the content or accuracy and does not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other materials, products, or services of third-parties.</p>
<p>Company is not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites regardless of the existence of any third party link on Platform. Please review carefully such third-party’s policies and practices and make sure to understand them before engaging in any transactions.</p>
<h3>INTELLECTUAL PROPERTY (IP) AND IP INFRINGEMENT</h3>
<b>Can User use the content published on Platform such as "Meramachine" mark when doing business with other parties?</b><br>
<p>Users may not use any trademark, service mark or logo of any independent third parties without prior written approval from such parties.
"Meramachine" and related icons and logos whether registered or unregistered are the trademarks of the Company and are protected under applicable copyright, trademark and other proprietary and intellectual property laws. Users’ unauthorized adoption copying, modification, use or publication of these marks is strictly prohibited.<br>
Users must not modify the paper or digital copies of any materials printed or downloaded in any way, and they must not use any illustrations, photographs, video or audio sequences or any graphics separately from any accompanying text.<br>
Users must not use any part of the materials on Platform for commercial purposes without obtaining a licence to do so from Company. All rights, not otherwise claimed under this Agreement by Company are hereby reserved.<br>
User understands that Platform and software embodied within Platform may include security components that permit digital materials to be protected, and that use of these materials is subject to usage rules set by Company or other parties that facilitate the same. User agrees that it will not attempt to override, disable, circumvent or otherwise interfere with any such security components and usage rules embedded in the Platform.</p>
<p><b>How does the Company deal with IP infringement?</b></p>
<p>
Any trademark, word mark or intellectual property of any User(s) or Supplier(s) belongs to such User(s)/Supplier(s) alone, and Company has no right or claim over the same.<br>
Company reserves the right in its sole discretion to remove any material/content/photos/offers displayed on the Platform which in Company’s reasonable belief is unlawful or could subject Company to liability or is in violation of this Agreement or is otherwise found inappropriate in the Company’s opinion. Company reserves the right to cooperate with any investigation in this regard.<br>
Company reserves the right to suspend or terminate the account of a User as deemed appropriate by it. Users agree that the Company shall have no liability to any Users, including liability in respect of consequential or any other damages, in the event Company takes any of the actions pursuant to allegations of IP infringement.<br>
Users acknowledge and agree that Company is not an arbitrator or judge of disputes concerning intellectual property and it cannot, by any means, verify that any Supplier selling or supplying merchandise on the Platform have the right to sell the products. Company encourages Users to assist it in identifying listings on the Platform, which, according to Users’ knowledge or belief infringe their rights or third party rights.<br>
The delisting of product from Platform is to safeguard Company’s interest, by taking down a listing, Company does not and cannot be deemed to be endorsing a claim of infringement and further in those instances in which Company declines to take down a listing, Company does not and cannot be deemed to be endorsing that the listing is not infringing of third party rights or endorsing any sale or supply of merchandise or services pursuant to or on account of such listing.
We request you to review the Intellectual Property Policy available on the Application for more information.
</p>
<b style="font-size:15px;">DISCLAIMER AND LIABILITIES</b>
<br>
<b>What are the standard disclaimers in relation to the Platform and the Services?</b>
<p>Company, in no event, is or will be liable to User including the Reseller or anyone claiming through a User in respect of product or other User Transaction under contract, negligence, strict liability or other legal or equitable theory for any special, incidental, indirect, consequential, exemplary or punitive damages, loss of goodwill, loss of revenue, loss of opportunity, loss of anticipated profits, whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable or whether or not Company has been advised of the possibility of such damages, or based on any theory of liability, including breach of contract or warranty or negligence or any other claim arising out of or in connection with the use of or access of Platform.Company shall not be liable for: any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation any financial losses, loss of data, replacement costs, or any similar damages, whether based in contract, tort, strict liability or otherwise, arising from the use of Platform, or for any other claim related in any way to the use of the Application, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the Application/Platform or any content posted, transmitted, or otherwise made available via the Application/Platform, even if advised of their possibility.<br>
Users shall be solely responsible for damages, if any, to their data system or for loss of data arising from download of content from Platform. No guidance or information, written or oral, obtained from Company or via the Platform, shall constitute any warranty, unless stated otherwise.</p>
         
          
        </div>

      </div>
    </section>

   